name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: nykmaks/iit:latest

      - name: Deploy to Server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          DOCKER_IMAGE: nykmaks/iit:latest
        run: |
          echo "${SSH_KEY}" > key.pem
          cat key.pem
          chmod 400 key.pem
          ssh -i "key.pem" ${SSH_USER}@${SSH_HOST} << 'EOF'
              docker pull ${DOCKER_IMAGE}
              docker stop web-app || true
              docker rm web-app || true
              docker run -d -p 80:80 --name web-app ${DOCKER_IMAGE}
          EOF
          rm key.pem